### ISSUE TITLE
ACT 4 MAPA MENTAL COMUNICACION ORAL Y ESCRITA YAEL TRINIDAD

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-4-mapa-mental-YaelTrinidad#1]
[ACT 4 MAPA METAL C ORAL Y ESC YAEL TRINIDAD SPRINT 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-YaelTrinidad/files/9593042/ACT.4.MAPA.METAL.C.ORAL.Y.ESC.YAEL.TRINIDAD.SPRINT.2.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 4
Obtuviste un 18.4% de los 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
